//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.18 at 03:50:01 PM BST 
//


package atg.userprofiling.email.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "groupOrTransUnitOrBinUnit"
})
@XmlRootElement(name = "body")
public class Body {

    @XmlElements({
        @XmlElement(name = "group", type = Group.class),
        @XmlElement(name = "trans-unit", type = TransUnit.class),
        @XmlElement(name = "bin-unit", type = BinUnit.class)
    })
    protected List<Object> groupOrTransUnitOrBinUnit;

    /**
     * Gets the value of the groupOrTransUnitOrBinUnit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the groupOrTransUnitOrBinUnit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroupOrTransUnitOrBinUnit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Group }
     * {@link TransUnit }
     * {@link BinUnit }
     * 
     * 
     */
    public List<Object> getGroupOrTransUnitOrBinUnit() {
        if (groupOrTransUnitOrBinUnit == null) {
            groupOrTransUnitOrBinUnit = new ArrayList<Object>();
        }
        return this.groupOrTransUnitOrBinUnit;
    }

}
