//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.18 at 03:50:01 PM BST 
//


package atg.userprofiling.email.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contextGroup",
    "countGroup",
    "propGroup",
    "note",
    "groupOrTransUnitOrBinUnit"
})
@XmlRootElement(name = "group")
public class Group {

    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String id;
    @XmlAttribute(name = "datatype")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String datatype;
    @XmlAttribute(name = "xml:space")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String xmlSpace;
    @XmlAttribute(name = "ts")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String ts;
    @XmlAttribute(name = "restype")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String restype;
    @XmlAttribute(name = "resname")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String resname;
    @XmlAttribute(name = "extradata")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String extradata;
    @XmlAttribute(name = "extype")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String extype;
    @XmlAttribute(name = "help-id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String helpId;
    @XmlAttribute(name = "menu")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String menu;
    @XmlAttribute(name = "menu-option")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String menuOption;
    @XmlAttribute(name = "menu-name")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String menuName;
    @XmlAttribute(name = "coord")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String coord;
    @XmlAttribute(name = "font")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String font;
    @XmlAttribute(name = "css-style")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String cssStyle;
    @XmlAttribute(name = "style")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String style;
    @XmlAttribute(name = "exstyle")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String exstyle;
    @XmlElement(name = "context-group")
    protected List<ContextGroup> contextGroup;
    @XmlElement(name = "count-group")
    protected List<CountGroup> countGroup;
    @XmlElement(name = "prop-group")
    protected List<PropGroup> propGroup;
    protected List<Note> note;
    @XmlElements({
        @XmlElement(name = "group", type = Group.class),
        @XmlElement(name = "trans-unit", type = TransUnit.class),
        @XmlElement(name = "bin-unit", type = BinUnit.class)
    })
    protected List<Object> groupOrTransUnitOrBinUnit;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the datatype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatatype() {
        return datatype;
    }

    /**
     * Sets the value of the datatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatatype(String value) {
        this.datatype = value;
    }

    /**
     * Gets the value of the xmlSpace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlSpace() {
        if (xmlSpace == null) {
            return "default";
        } else {
            return xmlSpace;
        }
    }

    /**
     * Sets the value of the xmlSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlSpace(String value) {
        this.xmlSpace = value;
    }

    /**
     * Gets the value of the ts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTs() {
        return ts;
    }

    /**
     * Sets the value of the ts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTs(String value) {
        this.ts = value;
    }

    /**
     * Gets the value of the restype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestype() {
        return restype;
    }

    /**
     * Sets the value of the restype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestype(String value) {
        this.restype = value;
    }

    /**
     * Gets the value of the resname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResname() {
        return resname;
    }

    /**
     * Sets the value of the resname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResname(String value) {
        this.resname = value;
    }

    /**
     * Gets the value of the extradata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtradata() {
        return extradata;
    }

    /**
     * Sets the value of the extradata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtradata(String value) {
        this.extradata = value;
    }

    /**
     * Gets the value of the extype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtype() {
        return extype;
    }

    /**
     * Sets the value of the extype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtype(String value) {
        this.extype = value;
    }

    /**
     * Gets the value of the helpId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHelpId() {
        return helpId;
    }

    /**
     * Sets the value of the helpId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHelpId(String value) {
        this.helpId = value;
    }

    /**
     * Gets the value of the menu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMenu() {
        return menu;
    }

    /**
     * Sets the value of the menu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMenu(String value) {
        this.menu = value;
    }

    /**
     * Gets the value of the menuOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMenuOption() {
        return menuOption;
    }

    /**
     * Sets the value of the menuOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMenuOption(String value) {
        this.menuOption = value;
    }

    /**
     * Gets the value of the menuName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * Sets the value of the menuName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMenuName(String value) {
        this.menuName = value;
    }

    /**
     * Gets the value of the coord property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoord() {
        return coord;
    }

    /**
     * Sets the value of the coord property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoord(String value) {
        this.coord = value;
    }

    /**
     * Gets the value of the font property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFont() {
        return font;
    }

    /**
     * Sets the value of the font property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFont(String value) {
        this.font = value;
    }

    /**
     * Gets the value of the cssStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCssStyle() {
        return cssStyle;
    }

    /**
     * Sets the value of the cssStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCssStyle(String value) {
        this.cssStyle = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyle(String value) {
        this.style = value;
    }

    /**
     * Gets the value of the exstyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExstyle() {
        return exstyle;
    }

    /**
     * Sets the value of the exstyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExstyle(String value) {
        this.exstyle = value;
    }

    /**
     * Gets the value of the contextGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contextGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContextGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContextGroup }
     * 
     * 
     */
    public List<ContextGroup> getContextGroup() {
        if (contextGroup == null) {
            contextGroup = new ArrayList<ContextGroup>();
        }
        return this.contextGroup;
    }

    /**
     * Gets the value of the countGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the countGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCountGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CountGroup }
     * 
     * 
     */
    public List<CountGroup> getCountGroup() {
        if (countGroup == null) {
            countGroup = new ArrayList<CountGroup>();
        }
        return this.countGroup;
    }

    /**
     * Gets the value of the propGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the propGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPropGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropGroup }
     * 
     * 
     */
    public List<PropGroup> getPropGroup() {
        if (propGroup == null) {
            propGroup = new ArrayList<PropGroup>();
        }
        return this.propGroup;
    }

    /**
     * Gets the value of the note property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the note property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Note }
     * 
     * 
     */
    public List<Note> getNote() {
        if (note == null) {
            note = new ArrayList<Note>();
        }
        return this.note;
    }

    /**
     * Gets the value of the groupOrTransUnitOrBinUnit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the groupOrTransUnitOrBinUnit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroupOrTransUnitOrBinUnit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Group }
     * {@link TransUnit }
     * {@link BinUnit }
     * 
     * 
     */
    public List<Object> getGroupOrTransUnitOrBinUnit() {
        if (groupOrTransUnitOrBinUnit == null) {
            groupOrTransUnitOrBinUnit = new ArrayList<Object>();
        }
        return this.groupOrTransUnitOrBinUnit;
    }

}
