//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.18 at 03:50:01 PM BST 
//


package atg.userprofiling.email.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the atg.cloud.notifications.email package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: atg.cloud.notifications.email
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BinTarget }
     * 
     */
    public BinTarget createBinTarget() {
        return new BinTarget();
    }

    /**
     * Create an instance of {@link InternalFile }
     * 
     */
    public InternalFile createInternalFile() {
        return new InternalFile();
    }

    /**
     * Create an instance of {@link ExternalFile }
     * 
     */
    public ExternalFile createExternalFile() {
        return new ExternalFile();
    }

    /**
     * Create an instance of {@link AltTrans }
     * 
     */
    public AltTrans createAltTrans() {
        return new AltTrans();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link Target }
     * 
     */
    public Target createTarget() {
        return new Target();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link ContextGroup }
     * 
     */
    public ContextGroup createContextGroup() {
        return new ContextGroup();
    }

    /**
     * Create an instance of {@link PropGroup }
     * 
     */
    public PropGroup createPropGroup() {
        return new PropGroup();
    }

    /**
     * Create an instance of {@link Body }
     * 
     */
    public Body createBody() {
        return new Body();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link TransUnit }
     * 
     */
    public TransUnit createTransUnit() {
        return new TransUnit();
    }

    /**
     * Create an instance of {@link BinUnit }
     * 
     */
    public BinUnit createBinUnit() {
        return new BinUnit();
    }

    /**
     * Create an instance of {@link Xliff }
     * 
     */
    public Xliff createXliff() {
        return new Xliff();
    }

    /**
     * Create an instance of {@link File }
     * 
     */
    public File createFile() {
        return new File();
    }

    /**
     * Create an instance of {@link Sub }
     * 
     */
    public Sub createSub() {
        return new Sub();
    }

    /**
     * Create an instance of {@link Glossary }
     * 
     */
    public Glossary createGlossary() {
        return new Glossary();
    }

    /**
     * Create an instance of {@link Count }
     * 
     */
    public Count createCount() {
        return new Count();
    }

    /**
     * Create an instance of {@link Mrk }
     * 
     */
    public Mrk createMrk() {
        return new Mrk();
    }

    /**
     * Create an instance of {@link Bx }
     * 
     */
    public Bx createBx() {
        return new Bx();
    }

    /**
     * Create an instance of {@link BinSource }
     * 
     */
    public BinSource createBinSource() {
        return new BinSource();
    }

    /**
     * Create an instance of {@link Bpt }
     * 
     */
    public Bpt createBpt() {
        return new Bpt();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link CountGroup }
     * 
     */
    public CountGroup createCountGroup() {
        return new CountGroup();
    }

    /**
     * Create an instance of {@link PhaseGroup }
     * 
     */
    public PhaseGroup createPhaseGroup() {
        return new PhaseGroup();
    }

    /**
     * Create an instance of {@link Phase }
     * 
     */
    public Phase createPhase() {
        return new Phase();
    }

    /**
     * Create an instance of {@link Ex }
     * 
     */
    public Ex createEx() {
        return new Ex();
    }

    /**
     * Create an instance of {@link G }
     * 
     */
    public G createG() {
        return new G();
    }

    /**
     * Create an instance of {@link It }
     * 
     */
    public It createIt() {
        return new It();
    }

    /**
     * Create an instance of {@link Skl }
     * 
     */
    public Skl createSkl() {
        return new Skl();
    }

    /**
     * Create an instance of {@link Prop }
     * 
     */
    public Prop createProp() {
        return new Prop();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link Ept }
     * 
     */
    public Ept createEpt() {
        return new Ept();
    }

    /**
     * Create an instance of {@link Context }
     * 
     */
    public Context createContext() {
        return new Context();
    }

    /**
     * Create an instance of {@link Ph }
     * 
     */
    public Ph createPh() {
        return new Ph();
    }

    /**
     * Create an instance of {@link X }
     * 
     */
    public X createX() {
        return new X();
    }

}
