//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.18 at 03:50:01 PM BST 
//


package atg.userprofiling.email.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "source",
    "target",
    "countGroupOrNoteOrContextGroupOrPropGroupOrAltTrans"
})
@XmlRootElement(name = "trans-unit")
public class TransUnit {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String id;
    @XmlAttribute(name = "approved")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String approved;
    @XmlAttribute(name = "translate")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String translate;
    @XmlAttribute(name = "reformat")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String reformat;
    @XmlAttribute(name = "xml:space")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String xmlSpace;
    @XmlAttribute(name = "datatype")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String datatype;
    @XmlAttribute(name = "ts")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String ts;
    @XmlAttribute(name = "restype")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String restype;
    @XmlAttribute(name = "resname")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String resname;
    @XmlAttribute(name = "extradata")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String extradata;
    @XmlAttribute(name = "extype")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String extype;
    @XmlAttribute(name = "help-id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String helpId;
    @XmlAttribute(name = "menu")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String menu;
    @XmlAttribute(name = "menu-option")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String menuOption;
    @XmlAttribute(name = "menu-name")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String menuName;
    @XmlAttribute(name = "coord")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String coord;
    @XmlAttribute(name = "font")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String font;
    @XmlAttribute(name = "css-style")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String cssStyle;
    @XmlAttribute(name = "style")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String style;
    @XmlAttribute(name = "exstyle")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String exstyle;
    @XmlAttribute(name = "size-unit")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String sizeUnit;
    @XmlAttribute(name = "maxwidth")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String maxwidth;
    @XmlAttribute(name = "minwidth")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String minwidth;
    @XmlAttribute(name = "maxheight")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String maxheight;
    @XmlAttribute(name = "minheight")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String minheight;
    @XmlAttribute(name = "maxbytes")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String maxbytes;
    @XmlAttribute(name = "minbytes")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String minbytes;
    @XmlAttribute(name = "charclass")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String charclass;
    @XmlAttribute(name = "phase-name")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String phaseName;
    @XmlElement(required = true)
    protected Source source;
    protected Target target;
    @XmlElements({
        @XmlElement(name = "count-group", type = CountGroup.class),
        @XmlElement(name = "note", type = Note.class),
        @XmlElement(name = "context-group", type = ContextGroup.class),
        @XmlElement(name = "prop-group", type = PropGroup.class),
        @XmlElement(name = "alt-trans", type = AltTrans.class)
    })
    protected List<Object> countGroupOrNoteOrContextGroupOrPropGroupOrAltTrans;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the approved property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApproved() {
        return approved;
    }

    /**
     * Sets the value of the approved property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApproved(String value) {
        this.approved = value;
    }

    /**
     * Gets the value of the translate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranslate() {
        if (translate == null) {
            return "yes";
        } else {
            return translate;
        }
    }

    /**
     * Sets the value of the translate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranslate(String value) {
        this.translate = value;
    }

    /**
     * Gets the value of the reformat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReformat() {
        if (reformat == null) {
            return "yes";
        } else {
            return reformat;
        }
    }

    /**
     * Sets the value of the reformat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReformat(String value) {
        this.reformat = value;
    }

    /**
     * Gets the value of the xmlSpace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlSpace() {
        if (xmlSpace == null) {
            return "default";
        } else {
            return xmlSpace;
        }
    }

    /**
     * Sets the value of the xmlSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlSpace(String value) {
        this.xmlSpace = value;
    }

    /**
     * Gets the value of the datatype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatatype() {
        return datatype;
    }

    /**
     * Sets the value of the datatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatatype(String value) {
        this.datatype = value;
    }

    /**
     * Gets the value of the ts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTs() {
        return ts;
    }

    /**
     * Sets the value of the ts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTs(String value) {
        this.ts = value;
    }

    /**
     * Gets the value of the restype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestype() {
        return restype;
    }

    /**
     * Sets the value of the restype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestype(String value) {
        this.restype = value;
    }

    /**
     * Gets the value of the resname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResname() {
        return resname;
    }

    /**
     * Sets the value of the resname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResname(String value) {
        this.resname = value;
    }

    /**
     * Gets the value of the extradata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtradata() {
        return extradata;
    }

    /**
     * Sets the value of the extradata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtradata(String value) {
        this.extradata = value;
    }

    /**
     * Gets the value of the extype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtype() {
        return extype;
    }

    /**
     * Sets the value of the extype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtype(String value) {
        this.extype = value;
    }

    /**
     * Gets the value of the helpId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHelpId() {
        return helpId;
    }

    /**
     * Sets the value of the helpId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHelpId(String value) {
        this.helpId = value;
    }

    /**
     * Gets the value of the menu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMenu() {
        return menu;
    }

    /**
     * Sets the value of the menu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMenu(String value) {
        this.menu = value;
    }

    /**
     * Gets the value of the menuOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMenuOption() {
        return menuOption;
    }

    /**
     * Sets the value of the menuOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMenuOption(String value) {
        this.menuOption = value;
    }

    /**
     * Gets the value of the menuName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * Sets the value of the menuName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMenuName(String value) {
        this.menuName = value;
    }

    /**
     * Gets the value of the coord property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoord() {
        return coord;
    }

    /**
     * Sets the value of the coord property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoord(String value) {
        this.coord = value;
    }

    /**
     * Gets the value of the font property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFont() {
        return font;
    }

    /**
     * Sets the value of the font property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFont(String value) {
        this.font = value;
    }

    /**
     * Gets the value of the cssStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCssStyle() {
        return cssStyle;
    }

    /**
     * Sets the value of the cssStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCssStyle(String value) {
        this.cssStyle = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyle(String value) {
        this.style = value;
    }

    /**
     * Gets the value of the exstyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExstyle() {
        return exstyle;
    }

    /**
     * Sets the value of the exstyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExstyle(String value) {
        this.exstyle = value;
    }

    /**
     * Gets the value of the sizeUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizeUnit() {
        return sizeUnit;
    }

    /**
     * Sets the value of the sizeUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizeUnit(String value) {
        this.sizeUnit = value;
    }

    /**
     * Gets the value of the maxwidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxwidth() {
        return maxwidth;
    }

    /**
     * Sets the value of the maxwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxwidth(String value) {
        this.maxwidth = value;
    }

    /**
     * Gets the value of the minwidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinwidth() {
        return minwidth;
    }

    /**
     * Sets the value of the minwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinwidth(String value) {
        this.minwidth = value;
    }

    /**
     * Gets the value of the maxheight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxheight() {
        return maxheight;
    }

    /**
     * Sets the value of the maxheight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxheight(String value) {
        this.maxheight = value;
    }

    /**
     * Gets the value of the minheight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinheight() {
        return minheight;
    }

    /**
     * Sets the value of the minheight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinheight(String value) {
        this.minheight = value;
    }

    /**
     * Gets the value of the maxbytes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxbytes() {
        return maxbytes;
    }

    /**
     * Sets the value of the maxbytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxbytes(String value) {
        this.maxbytes = value;
    }

    /**
     * Gets the value of the minbytes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinbytes() {
        return minbytes;
    }

    /**
     * Sets the value of the minbytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinbytes(String value) {
        this.minbytes = value;
    }

    /**
     * Gets the value of the charclass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCharclass() {
        return charclass;
    }

    /**
     * Sets the value of the charclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCharclass(String value) {
        this.charclass = value;
    }

    /**
     * Gets the value of the phaseName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhaseName() {
        return phaseName;
    }

    /**
     * Sets the value of the phaseName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhaseName(String value) {
        this.phaseName = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link Source }
     *     
     */
    public Source getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link Source }
     *     
     */
    public void setSource(Source value) {
        this.source = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link Target }
     *     
     */
    public Target getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link Target }
     *     
     */
    public void setTarget(Target value) {
        this.target = value;
    }

    /**
     * Gets the value of the countGroupOrNoteOrContextGroupOrPropGroupOrAltTrans property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the countGroupOrNoteOrContextGroupOrPropGroupOrAltTrans property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCountGroupOrNoteOrContextGroupOrPropGroupOrAltTrans().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CountGroup }
     * {@link Note }
     * {@link ContextGroup }
     * {@link PropGroup }
     * {@link AltTrans }
     * 
     * 
     */
    public List<Object> getCountGroupOrNoteOrContextGroupOrPropGroupOrAltTrans() {
        if (countGroupOrNoteOrContextGroupOrPropGroupOrAltTrans == null) {
            countGroupOrNoteOrContextGroupOrPropGroupOrAltTrans = new ArrayList<Object>();
        }
        return this.countGroupOrNoteOrContextGroupOrPropGroupOrAltTrans;
    }

}
